//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Craft.Domain.Resources;

using System;
using System.Globalization;
using System.Resources;

/// <summary>
/// A strongly-typed resource class for looking up localized strings.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[System.Diagnostics.DebuggerNonUserCode()]
[System.Runtime.CompilerServices.CompilerGenerated()]
public static class DomainResources
{
    private static ResourceManager? _resourceManager;

    /// <summary>
    /// Returns the cached ResourceManager instance used by this class.
    /// </summary>
    public static ResourceManager ResourceManager
    {
        get
        {
            if (_resourceManager is null)
            {
                var temp = new ResourceManager("Craft.Domain.Resources.DomainResources", typeof(DomainResources).Assembly);
                _resourceManager = temp;
            }
            return _resourceManager;
        }
    }

    /// <summary>
    /// Gets or sets the culture used for resource lookups.
    /// </summary>
    public static CultureInfo? Culture { get; set; }

    /// <summary>
    /// Gets the localized string for AfterError: "{0} must be after {1}"
    /// </summary>
    public static string AfterError => ResourceManager.GetString("AfterError", Culture) ?? "{0} must be after {1}";

    /// <summary>
    /// Gets the localized string for LengthError: "{0} cannot be more than {1}"
    /// </summary>
    public static string LengthError => ResourceManager.GetString("LengthError", Culture) ?? "{0} cannot be more than {1}";

    /// <summary>
    /// Gets the localized string for RequiredError: "{0} is required"
    /// </summary>
    public static string RequiredError => ResourceManager.GetString("RequiredError", Culture) ?? "{0} is required";

    /// <summary>
    /// Gets the localized string for StartDateGreaterError: "Start must be before End"
    /// </summary>
    public static string StartDateGreaterError => ResourceManager.GetString("StartDateGreaterError", Culture) ?? "Start must be before End";

    /// <summary>
    /// Gets the localized string for RangeError: "{0} must be between {1} and {2}"
    /// </summary>
    public static string RangeError => ResourceManager.GetString("RangeError", Culture) ?? "{0} must be between {1} and {2}";

    /// <summary>
    /// Gets the localized string for MinLengthError: "{0} must be at least {1} characters"
    /// </summary>
    public static string MinLengthError => ResourceManager.GetString("MinLengthError", Culture) ?? "{0} must be at least {1} characters";

    /// <summary>
    /// Gets the localized string for MaxLengthError: "{0} must not exceed {1} characters"
    /// </summary>
    public static string MaxLengthError => ResourceManager.GetString("MaxLengthError", Culture) ?? "{0} must not exceed {1} characters";

    /// <summary>
    /// Gets the localized string for AlphabetAndSpecialCharError
    /// </summary>
    public static string AlphabetAndSpecialCharError => ResourceManager.GetString("AlphabetAndSpecialCharError", Culture) ?? "{0} must contain only alphabets (1st Uppercase) and ,.'() ";

    /// <summary>
    /// Gets the localized string for AlphaNumericError
    /// </summary>
    public static string AlphaNumericError => ResourceManager.GetString("AlphaNumericError", Culture) ?? "{0} must contain only alphanumeric characters (1st uppercase)";

    /// <summary>
    /// Gets the localized string for CapitalAlphabetError
    /// </summary>
    public static string CapitalAlphabetError => ResourceManager.GetString("CapitalAlphabetError", Culture) ?? "{0} must contain only uppercase letters";

    /// <summary>
    /// Gets the localized string for OnlyDigitError
    /// </summary>
    public static string OnlyDigitError => ResourceManager.GetString("OnlyDigitError", Culture) ?? "{0} must be a whole number";

    /// <summary>
    /// Gets the localized string for OnlyNumberError
    /// </summary>
    public static string OnlyNumberError => ResourceManager.GetString("OnlyNumberError", Culture) ?? "{0} must be a valid number";

    /// <summary>
    /// Gets the localized string for AlphaNumCodeWithHyphenRegExError
    /// </summary>
    public static string AlphaNumCodeWithHyphenRegExError => ResourceManager.GetString("AlphaNumCodeWithHyphenRegExError", Culture) ?? "{0} must contain only capital letters, digits and hyphen";

    /// <summary>
    /// Gets the localized string for FormatError
    /// </summary>
    public static string FormatError => ResourceManager.GetString("FormatError", Culture) ?? "{0} not in valid format";

    /// <summary>
    /// Gets the localized string for DuplicateError
    /// </summary>
    public static string DuplicateError => ResourceManager.GetString("DuplicateError", Culture) ?? "Value should not be same";

    /// <summary>
    /// Gets the localized string for ResourceNotFound
    /// </summary>
    public static string ResourceNotFound => ResourceManager.GetString("ResourceNotFound", Culture) ?? "The requested resource was not found";

    /// <summary>
    /// Gets the localized string for EntityNotFound: Entity "{0}" ({1}) was not found.
    /// </summary>
    public static string EntityNotFound => ResourceManager.GetString("EntityNotFound", Culture) ?? "Entity \"{0}\" ({1}) was not found.";

    /// <summary>
    /// Gets the localized string for EntityAlreadyExists
    /// </summary>
    public static string EntityAlreadyExists => ResourceManager.GetString("EntityAlreadyExists", Culture) ?? "Entity \"{0}\" ({1}) already exists.";

    /// <summary>
    /// Gets the localized string for ConcurrencyConflict
    /// </summary>
    public static string ConcurrencyConflict => ResourceManager.GetString("ConcurrencyConflict", Culture) ?? "A concurrency conflict occurred for entity \"{0}\" ({1}).";

    /// <summary>
    /// Gets the localized string for ValidationFailed
    /// </summary>
    public static string ValidationFailed => ResourceManager.GetString("ValidationFailed", Culture) ?? "One or more validation failures have occurred.";

    /// <summary>
    /// Gets the localized string for UnauthorizedAccess
    /// </summary>
    public static string UnauthorizedAccess => ResourceManager.GetString("UnauthorizedAccess", Culture) ?? "You are not authorized to access this resource.";

    /// <summary>
    /// Gets the localized string for ForbiddenAccess
    /// </summary>
    public static string ForbiddenAccess => ResourceManager.GetString("ForbiddenAccess", Culture) ?? "You do not have permission to perform this action.";

    /// <summary>
    /// Gets the localized string for InternalServerError
    /// </summary>
    public static string InternalServerError => ResourceManager.GetString("InternalServerError", Culture) ?? "An unexpected error occurred. Please try again later.";

    /// <summary>
    /// Gets the localized string for BadRequest
    /// </summary>
    public static string BadRequest => ResourceManager.GetString("BadRequest", Culture) ?? "The request was invalid or cannot be processed.";

    /// <summary>
    /// Gets the localized string for ConflictError
    /// </summary>
    public static string ConflictError => ResourceManager.GetString("ConflictError", Culture) ?? "A conflict occurred with resource \"{0}\": {1}";

    #region Formatting Helper Methods

    /// <summary>
    /// Formats the AfterError message with the provided parameters.
    /// </summary>
    public static string FormatAfterError(string fieldName, string comparisonFieldName)
        => string.Format(Culture, AfterError, fieldName, comparisonFieldName);

    /// <summary>
    /// Formats the LengthError message with the provided parameters.
    /// </summary>
    public static string FormatLengthError(string fieldName, int maxLength)
        => string.Format(Culture, LengthError, fieldName, maxLength);

    /// <summary>
    /// Formats the RequiredError message with the provided parameters.
    /// </summary>
    public static string FormatRequiredError(string fieldName)
        => string.Format(Culture, RequiredError, fieldName);

    /// <summary>
    /// Formats the RangeError message with the provided parameters.
    /// </summary>
    public static string FormatRangeError(string fieldName, object minValue, object maxValue)
        => string.Format(Culture, RangeError, fieldName, minValue, maxValue);

    /// <summary>
    /// Formats the MinLengthError message with the provided parameters.
    /// </summary>
    public static string FormatMinLengthError(string fieldName, int minLength)
        => string.Format(Culture, MinLengthError, fieldName, minLength);

    /// <summary>
    /// Formats the MaxLengthError message with the provided parameters.
    /// </summary>
    public static string FormatMaxLengthError(string fieldName, int maxLength)
        => string.Format(Culture, MaxLengthError, fieldName, maxLength);

    /// <summary>
    /// Formats the EntityNotFound message with the provided parameters.
    /// </summary>
    public static string FormatEntityNotFound(string entityName, object key)
        => string.Format(Culture, EntityNotFound, entityName, key);

    /// <summary>
    /// Formats the EntityAlreadyExists message with the provided parameters.
    /// </summary>
    public static string FormatEntityAlreadyExists(string entityName, object key)
        => string.Format(Culture, EntityAlreadyExists, entityName, key);

    /// <summary>
    /// Formats the ConcurrencyConflict message with the provided parameters.
    /// </summary>
    public static string FormatConcurrencyConflict(string entityName, object key)
        => string.Format(Culture, ConcurrencyConflict, entityName, key);

    /// <summary>
    /// Formats the ConflictError message with the provided parameters.
    /// </summary>
    public static string FormatConflictError(string resourceName, string reason)
        => string.Format(Culture, ConflictError, resourceName, reason);

    #endregion
}
