<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Authors>Sandeep SHARMA</Authors>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="11.0.0-rc.1.26425.128" />
	</ItemGroup>

	<ItemGroup>
		<None Include="buildTransitive\Craft.Expressions.props" Pack="true" PackagePath="buildTransitive\Craft.Expressions.props" />
	</ItemGroup>

</Project>
