<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Authors>Sandeep SHARMA</Authors>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Builders\**" />
		<EmbeddedResource Remove="Builders\**" />
		<None Remove="Builders\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="10.0.1">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Mapster" Version="10.0.12" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="10.0.11" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
		<PackageReference Include="xunit.v3" Version="4.0.0" />
		<PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="AutoFixture" Version="5.0.0-preview0012" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\1. Source\1. Core\Craft.Core\Craft.Core.csproj" />
		<ProjectReference Include="..\..\1. Source\1. Core\Craft.Domain\Craft.Domain.csproj" />
		<ProjectReference Include="..\..\1. Source\2. Data Access\Craft.Data\Craft.Data.csproj" />
		<ProjectReference Include="..\..\1. Source\2. Data Access\Craft.Repositories\Craft.Repositories.csproj" />
		<ProjectReference Include="..\..\1. Source\2. Data Access\Craft.QuerySpec\Craft.QuerySpec.csproj" />
		<ProjectReference Include="..\..\1. Source\5. Web\Craft.Controllers\Craft.Controllers.csproj" />
		<ProjectReference Include="..\..\1. Source\5. Web\Craft.HttpServices\Craft.HttpServices.csproj" />
	</ItemGroup>

</Project>
